import streamlit as st
import random

st.set_page_config(page_title="Estrazione Numeri", layout="wide")

# Aggiungi stile personalizzato (se necessario)
st.markdown("""
<style>
.big-font {
    font-size:24px !important;
}
</style>
""", unsafe_allow_html=True)

# Inizializza lo stato della sessione
if 'drawn_numbers' not in st.session_state:
    st.session_state.drawn_numbers = set()

if 'number' not in st.session_state:
    st.session_state.number = None
# Dizionario dei testi associati ai numeri
number_texts = {
    1: "L'Italia – La patria. Intesa sia come il nostro Paese che come la propria regione o città di provenienza, simbolo del legame alle proprie radici. Altri significati: Bambino, Capodanno, Capoufficio, Gennaio, Lunedì, Mare, Ministro, Pecora, Preghiera, Spartito, Tallone, Timbro, Trapano, Vulcano.",
    2: "'A piccerella – La bambina. Sognare una bambina o un bimbo maschio rimanda all’immaginario di famiglia tipico della cultura popolare italiana. Altri significati: Amore, Biberon, Brodo, Capra, Carosello, Martedì, Mela, Miniatura, Musulmano, Ottomano, Rubino, Testimone, Zodiaco",
    3: "'A jatta – La gatta. La gatta femmina (ma anche il gatto maschio) è un animale sfuggente e misterioso, secondo la superstizione il gatto nero porta sfortuna. Altri significati: Dado, Disprezzo, Dizionario, Gamba, Garofano, Granchio, Grembo, Guancia, Inferno, Lucciola, Marmo, Marzo, Mercoledì, Piede, Sale, Sultano, Temporale, Valigia.",
    4: "'O puorco – Il maiale. Altro animale della tradizione popolare italiana, è segno di abbondanza. Come illustra il celebre modo di dire, d’altronde, “del maiale non si butta via niente”. Altri significati: Aprile, Banda musicale, Batticuore, Bottoni, Commedia, Contadini, Fede, Fico, Fiore, Giovedì, Magia, Poltrona, Sabbia, Spinaci, Testa.",
    5: "'A mano – La mano. A questo concetto corrisponde il numero 5, proprio come cinque sono le dita, è una delle parti più importanti del corpo umano. Altri significati: Aglio, Albergatore, Allarme, Anguilla, Argenteria, Birra, Goffo, Lievito, Maggio, Merluzzo, Oratorio, Pendolo, Pera, Pittrice, Rabbia, Sordo, Tradimento, Venerdì.",
    6: "Chella che guarda 'nterra – Organo sessuale femminile. Come abbiamo spiegato in precedenza, molto spesso i numeri e il loro significato corrispondono ad allusioni più o meno “decifrabili”. Altri significati: Acquario, Addomesticare, Adulto, Antiquario, Bella donna, Bell’uomo, Borgo, Candelabro, Chirurgo, Comunione, Cravatta, Effemminato, Luna, Lutto, Maggiordomo, Marito, Medaglia, Mezzaluna, Mezzanotte, Oca, Onorevole, Padrigno, Paradiso, Pellicano, Pianista, Professoressa, Quaderno, Sabato, Schiavo, Sgabello, Stazione, Telescopio, Tessera, Trifoglio, Vipera.",
    7: "'O vaso – Il vaso di creta. Sognare un vaso, qualsiasi sia il materiale che lo compone, ma anche un barattolo o un contenitore, indica un oggetto adatto a riporre cibo, sognando la sazietà. Altri significati: Avemaria, Barometro, Calcio, Caldo, Cimitero, Delfino, Delitto, Detenuto, Dollaro, Fagiolo, Furgone, Paracadute, Procuratore, Regalo, Rosario, Salsiccia, Scalpello, Sorpresa, Tabaccaio, Villaggio.",
    8: "'A maronna – La madonna. non poteva mancare nell’elenco dei numeri Smorfia la figura religiosa per eccellenza insieme a Gesù, la Madonna, protagonista di sogni e visioni. Altri significati: Agosto, Alloro, Ballerina, Ciglio, Faccia, Fuoco, Gemma, Gola, Mutande, Nocciolo, Olio, Padre, Pantaloni, Piatto, Portamonete, Primogenito, Ragu’, Santo, Scultore, Sottoscala, Stinco, Usignolo.",
    9: "'A figliata – La figliolanza. Una variante del numero 2, “‘A piccerella”. Sognare tanti bambini rimanda alla famiglia e in particolare al passato e all’infanzia. Altri significati: Ceramica, Cintura, Codardo, Culla, Dadi, Fata, Frigorifero, Lenticchie, Lupa, Nobile, Notizia, Oliva, Paese, Platino, Rapanello, Resurrezione, Rifugio, Rospo, Spago, Spumante, Taccuino, Zizzania.",
    10: "'E fasule – I fagioli. Ancora un elemento della tradizione napoletana e italiana: i fagioli, alimento frugale ma indispensabile sulle tavole di una volta come in quelle attuali. Altri significati: Ananas, Anice, Batteria, Biancheria, Calamaro, Cannone, Dinosauro, Fragola, Lavagna, Macellaio, Mani, Maradona, Marea, Merenda, Merlo, Mummie, Ninfa, Nomade, Orzo, Ottobre, Padrona, Pellicciaio, Polenta, Porro, Ravioli, Scheletro, Schiena, Segretario, Spiaggia, Spilla, Squalo, Taverna, Zappa, Zefiro.",
    11: "'E suricille – I topi. Sebbene possano terrorizzare chi li sogna, i topolini sono in realtà associati alla povertà e alla mancanza, ad esempio il timore che i soldi prestati non tornino indietro. Altri significati: Abadessa, Alunno, Aquila, Barattolo, Biblioteca, Cella, Cetrioli, Cicala, Cioccolata, Collina, Diario, Erba, Fratello maggiore, Micetti, Mattino, Moglie, Novembre, Nudo, Ottone, Pantofole,Scala, Schiaffo, Sentinella, Singhiozzo, Sorella, Vacca, Zabaione, Zia, Zucca.",
    12: "'E surdate – Il soldato. Un personaggio caratteristico della storia italiana, incarna l’idea di virilità e potenza anche se spesso è abbinato a guerra e cattive notizie in arrivo. Altri significati: Alice, Apostoli, Arca, Biscotti, Bretelle, Cerchio, Cibi, Corallo, Defunto, Dei, Droga, Fabbrica, Gelato, Gelsomino, Lotto, Marmellata, Mattina, Medici, Metropolitana, Minestrone, Orecchie, Pioggia, Pulcino, Salvadanaio, Sonnambulo, Spazzino, Vanità, Veterinario.",
    13: "Sant' Antonio. Numero dedicato a Sant’Antonio da Padova, detto il Santo dei Miracoli, la cui festa cade il 13 giugno. Si tratta di uno dei simboli più attesi e nell’immaginario comune è il numero portafortuna per eccellenza. Altri significati: Amanti, Candela, Fritto, Ingegnere, Lago, Laguna, Lattuga, Magistero, Morte, Principe, Rana, Rimedio, Salto, Scarabeo, Tombola, Violino.",
    14: "'O mbriaco – L'ubriaco. Figura che è possibile sognare in diversi contesti, come nelle piazze o nei vicoli, solitamente allegro e vagabondo. Altri significati: Bancarotta, Barile, Baule, Borsa, Capsula, Cassa, Cerotto, Cofano, Collezione, Cuscino, Ferrovia, Filastrocca, Gambero, Imprenditore, Incinta, Incornare, Libertà, Madama, Mastino, Montanaro, Morire, Pentagono, Picchio, Pompa, Porcile, Rete, Seta, Specchio, Stagno, Timone, Zaffiro, Zoppo.",
    15: "'O guaglione – Il ragazzo. Nella tradizione il ragazzo rappresenta un individuo poco più che adolescente, desideroso di fare e di scoprire il mondo. Altri significati: Abbigliamento, Benedettino, Bisonte, Buccia, Calze, Cardinale, Ferragosto, Fiocco, Firma, Idraulico, Nano, Ortolano, Passaporto, Passerotto, Pino, Poesia, Re, Rinoceronte, Scacchi, Sonno, Sovrano, Turchese, Uccello.",
    16: "'O culo – Il deretano. Ancora un simbolo abbinato all’anatomia umana, in questo caso rappresenta anche un bel colpo di fortuna e per questo è molto ambito. Altri significati: Confessore, Cucire, Dedicare, Farmacia, Funerale, Grillo, Gufo, Magro, Malaria, Occhio, Ottico, Peperone, Regno, Talismano, Tenaglia, Tosse, Turista, Venditore.",
    17: "'A disgrazia – La sfortuna. Il numero della sfortuna per antonomasia è proprio il 17, che può indicare in senso più ampio malasorte, malocchio, disgrazie e cattivi presagi. Altri significati: Amica, Barca, Barone, Bisca, Cervo, Conservatorio, Crema, Gondola, Grembiule, Insetto, Libreria, Lombardo, Lusso, Minorenne, Mucca, Mutilato, Nonna, Smorfia, Sterco, Tabacco.",
    18: "'O sanghe – Il sangue. L’essenza della vita umana, nei sogni può rappresentare anche timori e sofferenze che appaiono appena l’incoscio si rilassa, proprio durante il sonno. Altri significati: Apostolo, Appartamento, Arlecchino, Artiglieria, Carabiniere, Cesso, Coltellata, Fiammifero, Insalata, Monumento, Naso, Orfano, Reame, Rosa, Sacrestia, Sapone, Scrofa, Serenata, Tarocco, Vedova, Veleno.",
    19: "'A resata – La risata. Un suono di gioia e allegria, ma anche di scherno. Indica spontaneità e rumore spensierato. Altri significati: Amico, Anello, Ballerini, Bicchieri, Cenere, Commissario, Contrabbandiere, Gioco, Mistero, Mitra, Nuda, Numeri, Oculista, Passione, Perditempo, Pianta con fiori, Prezzemolo, Ruggito, Sofà, Uva.",
    20: "'A festa – La festa. Vicino al numero 19 si trova il 20, “La festa”: non è un caso che queste due cifre siano rappresentate vicine, tra giochi e divertimento. Altri significati: Avena, Bestia, Brace, Carezze, Cartone, Cavoli, Coniglio, Depressione, Detective, Edificio, Fiume, Fornaio, Frutta, Gioiello, Girandola, Idiota, Ignorante, Luglio, Mozzo, Museo, Nausea, Pallone, Pellegrinaggio, Pellicola, Ricco, Sedia, Teatro, Telefono, Telegramma, Topo.",
    21: "'A femmena annura – La donna nuda. Rappresenta bellezza e desiderio, non sempre facili da raggiungere. Altri significati: Barbiere, Bestemmia, Camorra, Cavolfiore, Chiave, Cugino, Esattore, Geometra, Insulto, Lupo, Mercante, Navi, Negoziante, Polpetta, Radice, Salotto, Setta, Tegame, Tenore, Ufficiale, Vendemmia, Vergogna, Zitella.",
    22: "'O pazzo – Il pazzo. In abbinamento al numero 23, “Lo scemo”, indica colui che dà in escandescenza facilmente. Altri significati: Avarizia, Biglietto, Cappuccio, Carrozza, Coro, Dama gioco, Lapidare, Lucerna, Massaia, Merletto, Munizione, Nebbia, Orientale, Palude, Parroco, Pedina, Pesca, Pettegola, Pollice, Puzza, Spalla, Tacchino, Zingara.",
    23: "'O scemo – Lo scemo. Rappresenta un personaggio tipico della commedia napoletana, ingenuo e sempliciotto, quasi mai animato da cattive intenzioni. Altri significati: Asino, Avvocato, Banda militare, Bufera, Castello, Corda, Cotone, Gendarme, Gettone, Giornale, Governo, Guinzaglio, Maiali, Profeta, Quaderni, Scimmia, Selva, Sopracciglia.",
    24: "'E gguardie – Le guardie. Altra figura caratteristica della tradizione popolare italiana, rigorosamente in divisa. Altri significati: Anziano, Arciprete, Arrosto, Avorio, Borraccia, Cameriere, Carceriere, Cavallo, Disoccupato, Donna, Girasole, Graffio, Mago, Manifestazione, Monarchia, Negligenza, Noce, Obesa, Orologio, Pappagallo, Patrono, Penitenza, Permaloso, Pesce, Pizza, Portiera, Saliera, Sole, Terme, Tipografia, Zibibbo.",
    25: "Natale: il giorno di Natale. Feesta fondamentale per i napoletani e gli italiani, sia per motivi religiosi che di convivialità. Altri significati: Atleta, Attrice, Bastioni, Clausura, Cliente, Colonnello, Direttore, Disavventura, Falsario, Fantasma, Figlia, Infedele, Lattaio, Legna, Liocorno, Olimpiade, Olocausto, Paglia, Pastiera, Petrolio, Pietà, Presepio, Riposo, Sconfitta, Settimana, Uccidere.",
    26: "Nanninella – Diminutivo del nome Anna. Per la tradizione religiosa è la madre della Madonna e viene festeggiata il 26 luglio, motivo per il quale è abbinata al numero 26. Altri significati: Calice, Calzolaio, Capperi, Casseruola, Cucchiaio, Deputato, Elmo, Europa, Fagiano, Fantino, Granatiere, Inchiostro, Lotteria, Lucchetto, Maccheroni, Maleficio, Mele, Messa, Moneta, Quarantena, Rivale, Talpa, Tarantola, Tovaglia, Ufficio, Veggente.",
    27: "'O cantero – L’orinale. Un simbolo triviale, metafora di un oggetto ormai in disuso, un tempo presente in ogni casa. Altri significati: Anatra, Attore, Caramelle, Cinema, Duello, Eclissi del sole, Enigma, Fante, Gemello, Letteratura, Lite, Magistratura, Nostalgia, Pilota, Pollame, Rapporto sessuale, Salmone, Sarcofago, Silenzio, Smemorato, Tartaruga, Torneo, Turbante.",
    28: "'E zzizze – Il seno femminile. In abbinamento alle figure femminili rappresenta la donna, fonte di vita e nutrimento. Altri significati: Aborto, America, Architetto, Bagaglio, Buco, Canestro, Canto, Capponi, Cassazione, Civetta, Codice civile, Equipaggio, Ermellino, Flotta, Liceo, Maestra, Mammelle, Omicidio, Orina, Panettiere, Prete, Sacerdote, Venere, Zucchero.",
    29: "'O pate d''e criature – Il padre dei bimbi. L’organo sessuale maschile: altra allusione simbolica molto chiara e talvolta considerata come benaugurale. Altri significati: Barba, Barcaioli, Berretto, Bombardiere, Branco, Cervello, Colla, Coma, Diamante, Erezione, Ferire, Gelsomino, Gesuita, Lampone, Lucertola, Ombrello, Parasole, Preservativo, Rissa, Rovina, Saetta, Scacchiera, Siringa.",
    30: "'E palle d''o tenente – Le palle del tenente. L'organo sessuale maschile: ancora un’allusione a virilità e sicurezza date dall’autorevolezza della figura militare rappresentata dal tenente. Altri significati: Acrobata, Caciotta, Capezzolo, Corista, Croce, Eremita, Ferramenta, Folla, Formaggio, Genitore, Gente, Gruppo, Italia, Labbra, Maga, Mese, Muratore, Muso, Nascita, Orgia, Ozio, Paladino, Pazienza, Querela, Scherzo, Seminario, Tomba, Uccidersi, Udito.",
    31: "'O padrone 'e casa – Il proprietario della casa. Simboleggia la responsabilità e l’affidabilità, è colui che possiede l’edificio e quindi ha stabilità economica e decisionale.",
    32: "'O capitone – Il capitone. Si tratta dell’animale simbolo della cena di “magro” della Vigilia di Natale. Altri significati: Anniversario, Apocalisse, Arcangelo, Balestra, Barbabietola, Bicicletta, Brigadiere, Briscola, Concerto, Conchiglia, Doccia, Donnaiolo, Epitaffio, Esploratore, Flipper, Forchetta, Lava, Mascalzone, Menzogna, Mortadella, Mummia egiziana, Omelia, Patata, Piombo, Scrigno, Stampatore, Stomaco, Suola, Tegola, Vicino di casa.",
    33: "L'anne 'e Cristo – Gli anni di Cristo. Questa metafora rappresenta il sacrificio del Figlio di Dio. Altri significati: Alveare, Amo da pesca, Aquila, Bastimento, Cabala, Caffè, Complotto, Crocifisso, Elica, Gazzettino, Gesù Cristo, Giraffa, Incudine, Latte, Ospedale, Panorama, Papavero, Parente, Revolver, Salame, Scommessa.",
    34: "'A capa – La testa. Ancora una volta la Smorfia fa cenno all’anatomia umana, il capo indica coscienza e razionalità. Altri significati: Ape, Città, Dea, Drago, Ferro, Giornalista, Missionario, Monaca, Motore, Nemico, Occhi, Ospedali, Radicchio, Re magi, Redazione, Rosso, Teschio, Tram, Viale, Vittoria, Zafferano.",
    35: "L'aucielluzz – L'uccello. Gli uccellini sono creature che possono volare, portatrici di buone notizie. Altri significati: Aeroplano, Angelo, Bachi da seta, Carote, Colazione, Dente, Dubbio, Energia, Esercito, Gelone, Ghigliottina, Gobba, Grondaia, Lasagna, Legislatore, Lume, Mozzarella, Nespola, Orto, Pellegrino, Perfido, Prosciutto, Tazza, Testicolo, Tintura, Trippa.",
    36: "'E ccastagnelle – Le nacchere. Importate grazie alle usanze spagnole, le nacchere sono uno strumento musicale “povero” ma efficace, utilizzato durante le danze popolari come la tarantella. Altri significati: Albergo, Carabinieri, Cittadini, Cotoletta, Gazzetta, Matrimonio, Meccanico, Nubile, Ombre, Orfana, Ristorante, Salice, Scorpione, Slavina, Tetto, Tresette, Valeriana, Vampiro, Vedovo, Vernice, Zolfo.",
    37: "'O monaco – Il frate. Figura religiosa, sognarne uno indica devozione e fede. Altri significati: Ammalati, Calzolaio, Confessione, Dattilografa, Dentista, Favola, Fusto, Imbroglio, Latticini, Leopardo, Losco, Miniera, Ovatta, Paragrafo, Patrigno, Pece, Pianoforte, Processione, Soldato, Sughero, Tempesta.",
    38: "'E mmazzate – Le bastonate. Nonostante le apparenze, sognare di prendere bastonate è segno di buona fortuna in arrivo. Altri significati: Abate, Affamato, Busta, Esca, Frate, Malvagità, Mostro, Nave, Nozze, Nuora, Ostaggio, Pigna, Pupille, Resina, Rossetto, Slitta, Tulipano, Valzer.",
    39: "'A funa 'nganna – La corda al collo. Rappresenta metaforicamente una sensazione di intrappolamento o di difficoltà nel trovare un’uscita. Altri significati: Acqua, Avvelenato, Cacao, Ciarlatano, Ciurma, Condannato, Eroe, Forca, Guanto, Neonato, Nidi, Ombrellaio, Oppio, Piattola, Poeta, Prato, Prugna, Spada, Tango, Ventaglio, Zattera.",
    40: "'A paposcia – L’ernia. È il sintomo di disagio fisico, fonte di fastidio e avvilimento. Altri significati: Alluminio, Apice, Ascella, Balcone, Birraio, Canottiere, Cattedra, Compare, Coperta, Coppola, Crimine, Danza, Discesa, Disgrazia, Esecuzione, Fiore, Forno, Giustiziere, Goloso, Indegno, Infermiere, Lampo, Malaugurio, Maligno, Manicotto, Mollica, Monarca, Muro, Natura, Neo, Nocciola, Notaio, Ombrello, Ossigeno, Osteria, Padrino, Pianerottolo, Piatti, Popolazione, Presidenza, Proprietà, Puledro, Puntura, Ragnatela, Rettile, Rito, Sambuco, Satellite, Scalatore, Scossa, Sgombro, Strada, Stuzzicadenti, Tagliatelle, Tonfo, Vettura, Visone.",
    41: "'O curtiello – Il coltello. Inteso come arma e non coltello da tavola, può essere un’allusione all’organo genitale maschile e quindi alla virilità. Altri significati: Acciughe, Agrumi, Album, Beduini, Calabrone, Contrabbando, Distretto, Dittatore, Golfo, Grattacielo, Imperatrice, Innocente, Legname, Libertino, Liquirizia, Lucernaio, Mania, Materasso, Mirtillo, Mosche, Mulino, Orfanello, Osso, Pappardelle, Piselli, Pittura, Platano, Plebeo, Processo, Punch, Sagittario, Sindaco, Smeraldo, Sparo, Stemma, Studente, Taglialegna.",
    42: "'O ccafè – Il caffè. Simbolo napoletano per eccellenza, indica accoglienza, atmosfera di festa e di convivialità, di quotidianità. Altri significati: Aeroporto, Bar, Baracca, Broccoli, Ciliegie, Corteccia, Drogheria, Fieno, Foglia, Gioco del Lotto, Labirinto, Latrato, Lucertolone, Maniaco, Manna celeste, Mimosa, Nana, Primario, Ribes, Risaia, Rogo, Sacrilegio, Segreto, Tentazione, Tortura, Usuraio.",
    43: "'A femmena 'ncopp'' o balcone – La donna al balcone. Una donna pettegola, sciatta e discinta, sempre pronta a osservare i fatti degli altri. Altri significati: Arcobaleno, Arresto, Azzurro, Campana, Catena, Cena, Corredo, Ebreo, Medioevo, Ombelico, Palcoscenico, Pelle, Penna, Spazzolino, Tabella.",
    44: "'E ccancelle – Il carcere. Sognare una prigione simboleggia la punizione ma anche l’opportunità di fuga. Altri significati: Alcol, Assassinio, Assemblea, Astronomia, Biglietto lotteria, Budino, Buoi, Centauro, Cognome, Commercio, Dispensa, Epilettico, Equatore, Facchino, Facoltà, Finanziere, Frittata, Geloso, Inganno, Lampi e tuoni, Lotta, Macellaio, Malavita, Mandarino cinese, Multa, Muto, Parrucca, Pastorale vescovo, Pennelli, Primavera, Proletario, Pulce, Ricotta, Scoppio, Scuola, Udienza, Verdura.",
    45: "'O vino bbuono – Il buon vino. L’elemento che non può mancare durante feste e celebrazioni, ancora una volta la Smorfia trae ispirazione dalla rinomata convivialità napoletana. Altri significati: Bottegaio, Ciambella, Circolo, Colosso, Fegato, Fuga, Fungo, Gallo, Giustizia, Grappolo, Intestino, Ispettore, Locandiera, Macchia, Magrezza, Mediterraneo, Mezzogiorno, Opera, Oppio, Pasticcere, Peccato, Pensionato, Rondine, Scorciatoia, Sillabario, Tabernacolo, Tiglio.",
    46: "'E denare – I soldi. Simbolo ambivalente, visto che i soldi possono significare sia abbondanza che preoccupazione. Altri significati: Armeria, Automobile, Banchiere, Bue, Cieco, Colomba, Farro, Fattore, Fenice, Gatta, Infermi, Lazzarone, Malinconia, Manganello, Martello, Mina, Morfina, Napoletano, Ninnananna, Nutrice, Olivastro, Paffuto, Parodia, Pescivendolo, Pompiere, Pugnalata, Radiografia, Rasoio, Salasso, Salnitro, Seppia, Sottana, Spavento, Stormo, Strascico, Stufa, Torcicollo, Toro, Zampa, Zoo.",
    47: "'O muorto – Il morto. Sognare un morto rimanda in realtà alla sensazione di perdita e, contemporaneamente, alla volontà di mantenere legami per evitare che si spengano. Altri significati: Arte magica, Camera, Capitello, Cartella, Centenario, Depravato, Ippopotamo, Lattante, Montone, Narciso, Presidente, Rame, Ramo, Ricevitoria, Stanza, Suono, Svizzero, Terrorismo, Virus, Zolfanello.",
    48: "'O muorto che pparla – Il morto che parla. Anche in questo caso si ha a che fare con un simbolo fortunato, meglio ancora se si riesce a decifrare cosa dice, in modo da poterlo interpretare e poi, ovviamente, giocare. Altri significati: Barocco, Bevitore, Bomba, Carabina, Corpetto, Dentifricio, Febbre, Filosofo, Indecente, Invidioso, Levatrice, Limone, Polvere, Pozzanghera, Ruggine, Tamburino, Tartaro.",
    49: "'O piezzo 'e carne – Il pezzo di carne. Quando si sogna questo elemento il significato simbolico è quello dell’abbondanza e prosperità, in forma figurata. Altri significati: Bistecca, Datteri, Deposizione, Espropriazione, Filigrana, Lettore, Limoni, Malattia, Male, Manoscritto, Matricidio, Mummia, Nottambulo, Numero, Orda, Pirata, Questura, Rivoluzione, Sciopero, Stivale, Suocera, Utensile, Velocità.",
    50: "'O ppane – Il pane. Non può mancare sulla tavola quotidiana, quando compare è sempre segno di abbondanza e benessere. Altri significati: Accappatoio, Armadio, Ballatoio, Boccale, Borsaiolo, Bosco, Cappella, Catechismo, Cattedrale, Cera, Cloaca, Cocomero, Cognato, Coltivazione, Giudice, Lampione, Lettino, Liberalismo, Loggia, Maestro, Magico, Morto, Ostilità, Padrone, Pedale, Petto, Pialla, Piastrella, Pietanza, Pipa, Predatore, Procura, Rigurgito, Rimorso, Sciabola, Sella, Sidro, Sogno, Trattoria, Unguento, Uova, Vescica.",
    51: "'O ciardino – Il giardino. Si può sognare un giardino verdeggiante tanto quanto un giardino desolato: simboleggia felicità se è rigoglioso, tristezza se è arido. Altri significati: Acquedotto, Affitto, Argento, Bieta, Bietole, Cerino, Cespuglio, Ciotola, Colera, Collegio, Foro, Lavanda, Lebbroso, Lesione da ferita, Nicchia, Onorato, Patetico, Pinzetta, Placche, Pomo, Pretura, Rabbino, Refezione, Sacco, Sottoveste, Stella, Sudore, Suora, Tenda da campeggio, Tigre, Tramonto, Zio.",
    52: "'A mamma – La mamma. Rappresenta l’amore incondizionato, i legami, l’affetto, caratteristici della figura materna. Altri significati: Anziana, Carnevale, Defunti, Estorsione, Globo, Guscio, Indemoniato, Irlandese, Lazzaretto, Liuto, Marciapiede, Medico, Metallo, Monte, Muscoli, Orecchino, Orso, Ostie, Pagliaio, Pasqua, Pasta, Ponente, Possessione, Remo, Ricercato, Sciarpa, Sfera, Stampa, Viaggio.",
    53: "'O viecchio – Il vecchio. Quando si sogna una persona anziana ciò simboleggia una figura fragile ma autorevole grazie alla sua esperienza. Altri significati: Albero, Arco, Balordo, Bastimento, Bestemmiatore, Bidet, Capretto, Carciofi, Cocco, Cuoco, Madonna, Malandrina, Malanno, Nascondiglio, Oltremare, Orciolo, Pala, Penisola. ",
    54: "'O cappiello – Il cappello. Oggetto in grado di nascondere volontà e pensieri coprendo la testa. Altri significati: Avvoltoio, Bastonata, Borsellino, Carta, Ciuffo, Destino, Famiglia, Follia, Formica, Gelosa, Gelso, Ghiandola, Lontra, Maltrattamento, Merce, Montagna, Negro, Nero, Nitroglicerina, Orrore, Ortopedia, Pazzia, Quadri, Reale, Resistenza, Ripudio, Scoglio, Selvaggina, Soglia, Taralli, Tumore, Visita, Zinco.",
    55: "'A museca – La musica. Indica la leggerezza e la voglia di far festa. Altri significati: Bacchetta, Baci, Bue, Capelli, Capotreno, Ciclope, Classe, Fisarmonica, Fortezza, Giudeo, Gonorrea, Illecito, Incantesimo, Ira, Legislazione, Locusta, Magagna, Mercurio pianeta, Nespolo, Panchina, Perire, Petecchie, Poppante, Provola, Quadro, Quaresima, Resurrezione Cristo, Ricamo, Scopa, Sedano, Sgorbia.",
    56: "'A caruta – La caduta. Cadere nel vuoto simboleggia dover affrontare ansie e paure angoscianti. Altri significati: Asma, Azoto, Bolla, Buchi, Capoluogo, Cardellino, Casa, Castagne, Deposito, Emporio, Esilio, Falegname, Fanfara, Fascista, Guerra, Inappetenza, Indovinello, Mensola, Meridionale, Merlino, Miele, Officina, Ortensia, Paggio, Panzerotti, Paravento, Pariglia, Pericolo, Polpa, Pomodoro, Puzzolente, Racchetta, Rapina, Selvaggio, Seno, Tipografo, Tribunale, Ulcera, Vincita.",
    57: "'O scartellato – Il gobbo. Secondo la tradizione scaramantica, toccarne la gobba porta fortuna: è quindi un simbolo positivo e benaugurante. Altri significati: Agnelli, Arrotino, Bottiglia, Calamita, Finestra, Flauto, Gallina, Giovane, Infermiera, Libro, Magazziniera, Mammalucchi, Mediatore, Parlamento, Pavimento, Pellicceria, Pendaglio, Piantone, Rastrello, Sepolcro, Stecca, Treccia.",
    58: "'O paccotto – Il cartoccio. Proprio come l’oggetto che rappresenta, sognare un pacco significa la probabilità di regali in arrivo. Altri significati: Abitazione, Basilico, Bocciolo, Caffè espresso, Calunnia, Cannocchiale, Carrozziere, Cucina, Cuoio, Elefante, Erede, Locomotiva, Matrigna, Militare, Olive, Orata, Oriente, Orologiaio, Piroga, Radioscopia, Religioso, Stitichezza, Tamburo, Tappeto.",
    59: "'E pile – I peli. Significato metaforico: sia i capelli che i peli indicano forza e giovinezza. Altri significati: Barbuto, Baro, Bottino, Cagna, Canonica, Cavalletto, Cesta, Cipolle, Congiurato, Emisfero, Imprudenza, Italiano, Lavandai, Lenzuolo, Magazziniere, Melanzana, Mignolo, Pescheria, Pineta, Raffreddore, Scintilla, Tema, Torno, Triglia, Trota.",
    60: "Se Lamenta – Si lamenta. Il pianto e le lacrime sono la conseguenza di un dolore che va affrontato senza rimandare oltre. Altri significati: Cameriera, Cani, Canne, Capricorno, Certificato, Daino, Dentice, Divano, Dromedario, Epifania, Erario, Esequie, Fabbricato, Fanciulla, Farfalla, Figlio, Fucilazione, Gabella, Gomitolo, Ladri, Letargo, Luce, Mancino, Marchesa, Materassaio, Mazza, Nazione, Noccioli, Novella, Novizie, Oliveto, Palazzo, Palco, Panciuto, Parco, Pennacchi, Pentola, Piccione, Pilastro, Pizzicotto.",
    61: "'O cacciatore – Il cacciatore. Altro mestiere che indica energia e la possibilità di ricorrere ad aiuto per risolvere i problemi. Altri significati: Bancone, Benzina, Cane, Cattivo, Cupola, Doglie, Epidemia, Foschia, Gabbia, Gentiluomo, Gregge, Iettatore, Immoralità, Impostore, Incenso, Notai, Notturno, Oblazione, Organo, Oscillazione, Partigiano, Passante, Pena, Pettegolo, Salsa, Scarpa, Scienziato, Spugna, Straniero, Tendine, Terrorista, Vela, Zebra. Zingaro.",
    62: "'O muorto acciso – Il morto ammazzato. Sognare qualcuno che cessa di vivere a causa di una morte violenta significa in realtà allungare la vita al protagonista del sogno. Altri significati: Campioni, Cassiera, Coltello, Cornice, Elettricità, Ferie, Imene, Indizio, Infamia, Infante, Inondazione, Inzuccherare, Ipoteca, Norma, Odontalgia, Oro, Ostetricia, Patrocinio, Pietra, Piuma, Quadrupede, Reggimento, Registratore, Seminatore, Setaccio, Sirena, Vacanza.",
    63: "'A sposa – La sposa. È il segnale dell’inizio di una nuova vita gioiosa, proprio come la sposa nel suo abito bianco si appresta a cominciare la vita coniugale. Altri significati: Alluvione, Armata, Carovana, Fiera, Gabinetto, Grumo, Imperatore, Lama, Leone, Leonessa, Mattone, Molo, Mura, Nodo, Oroscopo, Ortaggio, Ozioso, Pantera, Perle, Sedile, Timo, Torcia, Trottola.",
    64: "'A sciammeria – La marsina. Una giacca da cerimonia, utilizzata storicamente da molti napoletani: indossarla in sogno significa esternare l’idea che si ha di sé. Altri significati: Arpa, Burla, Burro, Cigni, Collare, Confettura, Discoteca, Erbivoro, Ercole, Grotta, Guardia, Lavoro, Limetta, Martire, Metropoli, Napoletani, Nome, Nuoto, Ossario, Pallottoliere, Pepe, Pianura, Prigioniero, Rappresaglia, Scherma, Sfregio, Tovagliolo, Trave, Trespolo.",
    65: "'O chianto – Il pianto. Piangere in un sogno rappresenta il rilascio di tensione ed emozioni, non per forza negative. Altri significati: Anca, Autunno, Bambola, Bandito, Benefattore, Budella, Bugiardo, Burattini, Campane, Candela, Lacrime, Lanificio, Latrocinio, Lavoratore, Milza, Nembo, Olivaro, Paggi, Pangrattato, Ruscello, Saliera, Vecchiaia.",
    66: "'E ddoie zetelle – Le due zitelle. Solitamente due anziane non sposate, che passeggiano in coppia, come capitava non di rado in passato. Altri significati: Acquavite, Bara, Benestante, Canditi, Confetti, Corteo, Cresima, Elettori, Enciclopedia, Esplosione, Fulmine, Galleggiante, Gatto, Ginnastica, Gondoliere, Gozzo, Indifeso, Indipendenza, Lucentezza, Marchio, Mareggiata, Massa, Maternità, Miracolo, Misfatto, Morbillo, Originale, Padella, Palliativo, Panna, Paranco, Pasticceria, Piscina, Popolano, Pronostico, Pubblicazione, Pudore, Rifiuto, Ritratto, Rudere, Scudo, Serraglio, Solfeggio.",
    67: "'O totaro int''a chitarra – Il totano nella chitarra. Un’altra allusione goliardica, stavolta all’atto sessuale. Altri significati: Beccuccio, Camerino, Cappotto, Chiostro, Cisterna, Gabelliere, Giardiniere, Legume, Listello, Litografia, Lombrico, Madamigella, Marachella, Mastice, Melone, Mestiere, Mezzo, Moscerino, Orzata, Pennuto, Pozzo, Profumo, Rione, Tattica, Vergine.",
    68: "'A zuppa cotta – La minestra cotta. Indica il desiderio di appagamento emotivo, non solo della propria fame. Altri significati: Barboncino, Battimano, Bollore, Cacare, Canzone, Ceci, Combattimento, Cornacchia, Cotenna, Elezione, Fame, Fienile, Ginocchio, Gotta, Incavatura, Innaffiatoio, Maschio, Microscopio, Motoscafo, Nipote, Oracolo, Parere, Parolacce, Partenza, Peripezia, Placca, Ponte, Porta, Provvista, Restauratore, Ricettatore, Sasso, Tela, Temperino, Traguardo.",
    69: "Sott'e'ncoppo – Sottosopra. Ammiccamento allusivo ma anche riferimento alla forma grafica del numero 6 e del numero 9. Altri significati: Animale, Antipatico, Apparizione, Arcivescovo, Arteria, Banditore, Batticarne, Bergamotto, Campo, Carità, Cedri, Conigli, Crusca, Danzatore, Debito, Elemosina, Galoppo, Gonna, Licenza, Linguetta, Marionetta, Minatore, Pignatta, Polipo, Polmone, Prepotenza, Rammarico, Riconciliazione, Rotolo, Ruota, Spinta, Tirchio, Torta, Traffico, Tributo, Ulivo.",
    70: "'O palazzo – Il palazzo. Rappresenta una casa accogliente, oppure l’insieme di organi ed elementi del corpo umano. Altri significati: Anfora, Bandoliera, Cammello, Cappellaio, Cedola, Cerimonia, Distanza, Espressione, Fanciullo, Fazzoletto, Felpa, Fotografo, Foulard, Furto, Gargano, Geografia, Immondizia, Indice, Indovino, Invasione, Laurea, Letterato, Litorale, Malato, Malviventi, Marcia, Matematica, Matricola, Miccia, Negozio, Onorificenza, Orinare, Ostacolo, Palestra, Pareggio, Pendente, Pipistrello, Pistola, Pronipote, Proroga, Puntualità, Raccolta, Reato, Recinto, Reduce, Reggia, Regina, Ricetta, Sartoria, Sigaretta, Spettacolo, Struzzo, Tasso, Tavoletta, Zerbino.",
    71: "L'ommo 'e merda – L'uomo senza princìpi. Figura infida e disonesta, inaffidabile, molto sgradito nella vita come nella dimensione onirica. Altri significati: Allegria, Anfibio, Arcidiacono, Barcaiolo, Baronessa, Brillantina, Bugia, Capriola, Carro, Carte da gioco, Caserma, Ciclone, Colori, Cordoncino, Corvo, Cuore, Escremento, Farmacista, Gas, Gelo, Genio, Massoneria, Merda, Muffa, Occulto, Ortolana, Panciotto, Passione di Cristo, Pellegrini, Pizzaiola, Politecnico, Portabiancheria, Prigione, Rappresentante, Ricordo, Sagoma, Senatore, Sugo, Torre.",
    72: "'A meraviglia – Lo stupore. Simboleggia la sensazione di sollievo e meraviglia dopo situazioni spiacevoli. Altri significati: Aorta, Archivio, Avo, Bicocca, Cavallerizza, Democrazia, Discordia, Disdetta, Emozione, Falco, Giardini, Giove pianeta, Impotente, Inchino, Inciviltà, Isola, Lampada, Lesso, Lettiera, Lumaca, Medicina, Missione, Nave da guerra, Noioso, Nonno, Norcino, Olimpo, Pallottola, Paltò, Piazza, Pinnacolo, Pomata, Precisione, Presunzione, Previsione, Sfinge, Sposalizio, Strega.",
    73: "'O spitale – L'ospedale. Sognare un ospedale significa rivolgersi al luogo predefinito per la cura, dove si risolvono situazioni in sospeso, non solo a livello di salute. Altri significati: Braccio, Bussola, Consulto, Contrabbasso, Disonore, Esempio, Eunuco, Faro, Giacinti, Legittima, Mangione, Menta, Mercurio, Minaccia, Nefrite, Orazione, Orfanotrofio, Organista, Ormeggiare, Ortografia, Oscenità, Ossigenazione, Paesano, Pavone, Permuta, Prefetto, Primizie, Questore, Ricatto, Riccio, Sarda pesce, Sgorbio, Sobborgo, Stabilimento, Tappa, Turco.",
    74: "'A rotta – La grotta. In sogno è un rimando alla grotta della Natività, il luogo dove è nato Gesù Bambino. Altri significati: Amputazione, Antenato, Ascensione di Cristo, Bruttezza, Califfo, Filo, Foresta, Golf, Inquilino, Lana, Larghezza, Lettera d’amore, Litigio, Lode, Manette, Milady, Orribile, Pagliaccio, Palazzi, Palchetto, Pannocchia, Parrocchia, Pelliccia, Piombatura, Polpettone, Premio, Raucedine, Riso, Vagabondo.",
    75: "Pullecenella – Pulcinella. Rappresenta la maschera napoletana per eccellenza, un'adorabile canaglia, furba e portafortuna. Altri significati: Ambasciatore, Anguille, Autorità, Capitano, Capitombolo, Corsaro, Crivello, Curia, Ginepro, Ginestra, Giocatore, Glutine, Implacabile, Infinità, Iniezione, Macello, Mantello, Mascella, Orinatoio, Orticoltura, Ospitalità, Parrucchiere, Patrimonio, Persecuzione, Radio, Rugiada.",
    76: "'A funtana – La fontana. Il fluire dell’acqua in sogno è una metafora del fluire della vita. Altri significati: Baffi, Balena, Battaglia, Brontolone, Cadavere, Compagna, Dannato, Decoratore, Galanteria, Gemma preziosa, Guerrieri, Incendio, Indisciplinato, Invito, Ladra, Livido, Lunatico, Lunghezza, Lungo, Macelleria, Malaticcio, Malfattore, Marina, Mendicante, Miracoli, Monastero, Moribondo, Obbiezione, Operatore, Orchestra, Orecchioni, Organizzazione, Origine, Ovaia, Ovale, Panificio, Pentecoste, Pittore, Probabilità, Quartetto, Quota, Rancore, Tentativo, Tinozza.",
    77: "'E riavulille – I diavoli. Sinonimo di male, paura e dubbi, proprio come nella credenza religiosa popolare. Altri significati: Accademia, Agricoltore, Appello, Ascesso, Baccalà, Baciamano, Biada, Cancello, Carcerato, Cartoncino, Castagnole, Circuito, Corazza, Demone, Diavolo, Dieta, Fischietto, Folletto, Levante (vento), Liturgia, Lucido, Lucifero, Mecca, Mediocre, Mula, Nocchiero, Patriarca, Pattuglia, Pensione, Pignolo, Pizzaiolo, Protezione, Quarzo, Reumatismo, Spicchio, Tassa, Telepatia, Terno, Tromba, Volpe, Zuppa.",
    78: "'A bella figliola – La prostituta. Figura dalla connotazione negativa, rappresenta la superficialità e l’appariscenza. Altri significati: Amorosa, Antenna, Artista, Boccali, Cognata, Colpa, Colpo, Comando, Concubina, Cortile, Decreto, Divorzio, Ebano, Esito, Fidanzato/a, Fumo, Imbuto, Ingrato, Livello, Malefico, Mezzano, Mulatto, Nasello, Orchite, Organismo, Palpeggiamento, Parata, Pastura, Perdita, Pettinatura, Promessa, Prostituta, Puttana, Racconto, Rachitico, Rosmarino, Sinagoga, Vassoio.",
    79: "'O mariuolo – Il Ladro. Simboleggia minaccia e angoscia per sé o per la propria famiglia. Altri significati: Aculeo, Aia, Banca, Biscia, Braccia, Brigante, Bucato, Buio, Chitarra, Cinghiale, Convoglio, Editore, Frittella, Galeotto, Giallo, Gramigna, Guappo, Inno, Lavaggio, Lavatoio, Libidine, Lirica, Manigoldo, Mariuolo, Mestruazione, Mosca, Oliera, Oscurità, Piccante, Randello, Ribelle, Scrittoio, Sera, Tappo, Vapore, Vigili urbani.",
    80: "'A vocca – La bocca. Rappresenta la porta per l’anima, per la propria vita interiore. Altri significati: Aquilone, Arabo, Artefice, Bisturi, Boccaccia, Cartoleria, Castoro, Cinquina, Dignità, Fabbro, Francobollo, Fuochi d’artificio, Garanzia, Harem, Ignoto, Immaturità, Inaugurazione, Innamorato, Lanciere, Legale, Madreperla, Mattacchione, Melodramma, Meteora, Milione, Mosaico, Nobiltà, Occhiali, Patente, Plenilunio, Porcellana, Prodigio, Provolone, Quaglia, Radiazione, Salone, Sigaro, Sofferenza, Stravaganza, Tenda, Vento.",
    81: "'E sciure – I fiori. Simbolo di bellezza, rinascita e delicatezza. Altri significati: Aeronauta, Artisti, Bazar, Bolletta, Bordello, Camion, Campanello, Caverna, Ciondolo, Comandamento, Cornata, Devozione, Diploma, Ergastolo, Fronte, Gabbiano, Galantuomo, Gasometro, Guardiano, Iena, Incapace, Legnaia, Malerba, Malvagio, Mantiglia, Mente, Naufragio, Oppresso, Palafitta, Parlamentare, Quercia, Questione, Realtà, Seminarista, Sudario, Ulivo, Vino, Vino Marsala, Zampogna.",
    82: "'A tavula 'mbandita – La tavola imbandita. Indica la riunione della famiglia per celebrare qualcosa, segno di benessere e abbondanza. Altri significati: Abito, Arsenale, Asparagi, Camomilla, Cantante, Colpo pistola, Coppa, Deviazione, Dimenticanza, Esasperazione, Esclusione, Farina, Fava, Forbici, Governante, Itterizia, Maestrale, Mensa, Miglio, Occasione, Onore, Pagano, Palla, Pancia, Pistacchio, Pleura, Pranzo, Protesta, Protesto, Reo, Sacrestano, Sbirro, Scaldino, Seccatore, Sfilata, Tennis, Traghetto, Tremore, Trono, Vaticano.",
    83: "'O maletiempo – Il maltempo. Il brutto tempo in arrivo segnala presagi e cattive notizie in avvicinamento. Altri significati: Artrite, Bambino Gesù, Battistrada, Berlina, Bibbia, Bibliotecario, Bilancia, Carogna, Cocchieri, Codice, Cucchiaino, Defunta, Faretra, Felicità, Freccia, Frusta, Fucile, Grammo, Intirizzito, Inverno, Malalingua, Mangiatoia, Mostri, Operazione, Oscuramento, Ostia, Pagina, Pappafico, Peto, Pianta, Pigmeo, Pinacoteca, Profumeria, Purgatorio, Raggiro, Rapsodia, Ricchezza, Satiro, Scrittore, Sortilegio, Terracotta, Terrazza, Tintoria.",
    84: "'A cchiesa – La chiesa. È l’edificio dedicato al culto, sinonimo di guida e accoglienza. Altri significati: Astio, Bombola, Campanile, Cappellano, Cascina, Cassettone, Circoncisione, Duomo, Favilla, Feretro, Gestione, Granello sabbia, Lira (moneta), Maglia, Notte, Omaccio, Ortica, Ostricaio, Pacco, Paesana, Pagnotta, Palpebra, Papato, Pasciuto, Paternale, Pepiera, Pillola, Recipiente, Rimprovero, Riunione, Schifo, Sentiero, Tana, Tempio, Trampoli, Vaso, Zampe.",
    85: "Ll'aneme 'o priatorio – Le anime del purgatorio. Non ancora pronte per entrare in Paradiso, appaiono in sogno per chiedere ricordo e preghiere. Altri significati: Albume, Battesimo, Benessere, Boccia, Carbone, Cipressi, Corrispondenza, Equestre, Gavetta, Generazione, Ingiustizia, Inutile, Lebbrosa, Lente, Letamaio, Lettura, Marchese, Massacro, Moda, Oratore, Pagamento, Passivo, Pediluvio, Periferia, Pigrizia, Rabarbaro, Rene, Sacchetto, Sanatorio, Sperone, Strofa, Tartufo, Tecnico, Torchio.",
    86: "'A puteca – Il negozio. Le botteghe degli artigiani napoletani sono l’essenza del commercio e del folkore d Napoli. Altri significati: Agenzia, Ala, Annuncio, Aria, Associazione, Biglietto da visita, Cacca, Cartello, Caviglia, Cicoria, Cordone, Economo, Gabbia uccelli, Genesi, Impaurito, Inferriata, Logica, Manifesto, Moccolo, Moltiplicazione, Oppressione, Orgasmo, Pollaio, Prode, Rada, Salvagente, Scarafaggio, Signora, Statua, Timoniere, Vassallo, Vetro, Zuffa.",
    87: "'E perucchie – I pidocchi. Ssegno di sporcizia e disagio, possono simboleggiare anche azioni e pensieri negativi. Altri significati: Basilica, Brindisi, Ciabatte, Collera, Coriandolo, Diploma, Dogana, Gattone, Ginnasio, Guercio, Impertinente, Lealtà, Lord, Melagrano, Melodia, Miserabile, Moscerini, Nodi, Onnipotente, Palato, Palombaia, Parapetto, Parto, Paternità, Paternostro, Pezzente, Pollo, Povero, Purgante, Tastiera, Treno, Tubo.",
    88: "'E casecavalle – I caciocavalli. Altro simbolo di abbondanza, associato al numero 88 grazie al caratteristico aspetto del formaggio in questione. Altri significati: Annegato, Arancia, Armi, Barconi, Bersaglio, Bollo, Caparra, Chioccia, Collana d’oro, Comandante, Decrepito, Dialetto, Ebrei, Federa, Gemito, Grandine, Legge, Legittimità, Maculato, Maldicenza, Messaggio, Moto, Nevicare, Novizi, Odio, Opale, Orefice, Orticello, Pacchetto, Padiglione, Pedante, Pedata, Periodo, Piagnone, Pneumatici, Ricotta salata, Rilegatore, Rimborso, Scroto uomo, Serpente, Squadra, Sudicio, Tabaccaio, Tandem, Tribù.",
    89: "'A vecchia – La vecchia. Stesso significato del 53, “Il vecchio”, come omaggio alle radici e al rispetto per coloro che esistono da prima di noi. Altri significati: Bionda, Camposanto, Caraffa, Catenaccio, Ciclista, Cicogna, Contusione, Corna, Cuoca, Ebanista, Fastosità, Fattucchiera, Fratello, Gestazione, Ghiaia, Gravidanza, Iettatura, Invidia, Mulo, Neve, Nido, Pappa, Patibolo, Perversità, Pioppo, Principessa, Qualifica, Ragazzo, Salire, Sentenza giudiziaria, Serbatoio, Strage, Tagliola, Tavola, Termometro, Tirare, Tuono, Uomo, Voce.",
    90: "'A paura – La paura. Non è per forza un sogno negativo: spesso significa il timore prima di raggiungere un successo. Altri significati: Abbagliamento, Adunata, Aggressione, Ambiente, Ambulanza, Astrologia, Avaro, Bagliore, Bagnomaria, Becchino, Burrasca, Campione, Caprone, Cavaliere, Ceneri defunti, Circo, Civiltà, Coraggio, Cristallo, Custode, Debitore, Delinquente, Diagnosi, Diluvio, Dio, Dolce, Dolore, Epoca, Eredità, Eruzione, Eternità, Vangelo, Fama, Fortuna, Futuro, Generale, Gioielliere, Grasso, Gratitudine, Ingegno, Iride, Locanda, Lombaggine, Magistrato, Mentire, Mondo, Municipio, Muschio, Navale, Noia, Pantheon, Patria, Paura, Popolo, Prezzo, Progresso, Pubblicità, Quirinale, Ragazza, Rapimento, Redentore, Riscatto, Satana, Sfruttatore, Spaventapasseri, Stregone, Tenebra, Terremoto, Terrore, Trappola, Tutore, Valanga, Vespa, Zero.",
}

# Funzione per generare la griglia
def generate_grid():
    grid_html = '''
    <style>
    .grid-container {
        display: grid;
        grid-template-columns: repeat(10, 1fr);
        grid-template-rows: repeat(9, 1fr);
        gap: 2px;
        background-color: #006400; /* Verde del tavolo della roulette */
        padding: 5px;
    }
    .grid-item {
        background-color: #006400;
        color: white;
        text-align: center;
        font-size: 20px;
        padding: 10px;
    }
    .highlighted {
        background-color: #ff9999 !important; /* Rosso chiaro */
    }
    </style>
    <div class="grid-container">
    '''
    for i in range(1, 91):
        cls = 'grid-item'
        if i in st.session_state.drawn_numbers:
            cls += ' highlighted'
        grid_html += f'<div class="{cls}">{i}</div>'
    grid_html += '</div>'
    return grid_html

# Pulsante per estrarre un numero
if st.button('Estrai Numero'):
    remaining_numbers = set(range(1,91)) - st.session_state.drawn_numbers
    if remaining_numbers:
        new_number = random.choice(list(remaining_numbers))
        st.session_state.drawn_numbers.add(new_number)
        st.session_state.number = new_number
    else:
        st.write("Tutti i numeri sono stati estratti.")

# Mostra la griglia
grid_html = generate_grid()
st.markdown(grid_html, unsafe_allow_html=True)

# Visualizza l'ultimo numero estratto e il testo associato
if st.session_state.number:
    st.write(f"L'ultimo numero estratto è: **{st.session_state.number}**")
    st.write(f"**Significato:** {number_texts.get(st.session_state.number, 'Nessun testo disponibile per questo numero.')}")
